package moderation

// FeatureKey is the stable identifier for the core moderation feature (matches
// guild_feature_configs.feature_key and the dashboard route).
const FeatureKey = "moderation"

// AutomodKey is the stable identifier for the automod sub-feature. It is stored
// as a separate row so it can be toggled independently of manual moderation.
const AutomodKey = "automod"

// Config is the moderation feature's per-guild configuration (stored as JSONB
// and edited from the dashboard).
type Config struct {
	// LogChannel receives an embed for every moderation action (manual + automod).
	LogChannel string `json:"log_channel"`
	// DMOnAction DMs the affected user a notice when an action is taken.
	DMOnAction bool `json:"dm_on_action"`
}

// Default returns sensible moderation defaults.
func Default() Config {
	return Config{
		DMOnAction: true,
	}
}

// ── Automod: a rule-based engine ─────────────────────────────────────────────
//
// Automod is an ordered list of rules. Each rule pairs ONE detection trigger
// with a list of actions to take when it fires. Messages are screened against
// every enabled rule in order and the FIRST matching rule wins (its actions run;
// later rules are skipped for that message), which keeps behaviour predictable
// and avoids double-deleting or stacking timeouts.
//
// Repeat offenders are handled by the escalation ladder: actions can award
// infraction "points" that accumulate per user (with decay), and crossing a
// point threshold auto-applies a heavier action (timeout → kick → ban).
//
// This schema is mirrored in web/src/lib/moderation/automod.ts; keep the two in
// lockstep (json tags ↔ TS field names, the trigger/action catalogues, and the
// per-type field meanings documented below).

// AutomodConfig is the automod sub-feature's per-guild configuration.
type AutomodConfig struct {
	// Rules are evaluated in order; the first match wins for a given message.
	Rules []AutomodRule `json:"rules"`
	// Escalation is the cross-rule heat ladder driven by infraction points.
	Escalation Escalation `json:"escalation"`
	// ExemptRoles holders are never actioned by any rule (merged with per-rule).
	ExemptRoles []string `json:"exempt_roles"`
	// ExemptChannels are skipped by every rule (merged with per-rule exemptions).
	ExemptChannels []string `json:"exempt_channels"`
	// IgnoreBots skips messages authored by bots (default true).
	IgnoreBots bool `json:"ignore_bots"`
	// IgnoreMods skips members who can moderate (manage messages / ban / admin),
	// so staff are never caught by their own filters (default true).
	IgnoreMods bool `json:"ignore_mods"`
	// AlertChannel optionally receives a dedicated automod alert embed on every
	// hit, separate from the moderation mod-log ("" = post to the mod-log only).
	AlertChannel string `json:"alert_channel"`
}

// AutomodRule is one detection trigger plus the actions taken when it fires.
type AutomodRule struct {
	// ID is a stable identifier (generated by the editor, e.g. "rule_ab12cd").
	ID string `json:"id"`
	// Name is the human label shown in logs and the dashboard.
	Name string `json:"name"`
	// Enabled gates the rule; disabled rules are skipped entirely.
	Enabled bool `json:"enabled"`
	// Trigger is the single detection condition for this rule.
	Trigger RuleTrigger `json:"trigger"`
	// Exempt narrows this rule (in addition to the global exemptions).
	Exempt RuleExempt `json:"exempt"`
	// Actions run in order when the trigger fires.
	Actions []RuleAction `json:"actions"`
}

// RuleExempt is a per-rule allowance set.
type RuleExempt struct {
	Roles    []string `json:"roles,omitempty"`
	Channels []string `json:"channels,omitempty"`
}

// RuleTrigger is a tagged union keyed by Type. Only the fields relevant to a
// given Type are read; the rest stay zero. Type values are the Trigger*
// constants in catalog.go. Per-type field meanings:
//
//	words        Words + MatchMode (substring|word|wildcard), AllowList exempts terms
//	regex        Patterns (RE2), AllowList exempts matches
//	invites      AllowList = allowed invite codes / guild ids ("" blocks all invites)
//	links        LinkMode (all|allowlist|blocklist): allowlist→AllowList domains pass,
//	             blocklist→Domains are blocked
//	spam         Count messages within Window seconds (per user, any channel)
//	duplicates   Count identical messages within Window seconds (per user)
//	mentions     Limit = max distinct user mentions in one message
//	mass_mention Everyone (count @everyone/@here) and/or Roles (count role pings); Limit = max
//	caps         Limit = max % uppercase; MinLength ignores short messages
//	emojis       Limit = max emoji (unicode + custom) in one message
//	newlines     Limit = max newlines in one message
//	zalgo        Limit = max % combining marks (0 ⇒ a sane default)
//	spoilers     Limit = max ||spoiler|| spans in one message
//	attachments  Limit = max attachments in one message
//	account_age  Limit = minimum account age in HOURS (younger accounts trip it; on join)
//	name         Words/Patterns matched against Scan (username|nick|both) on join/update
type RuleTrigger struct {
	Type string `json:"type"`

	// Word / name matching.
	Words     []string `json:"words,omitempty"`
	MatchMode string   `json:"match_mode,omitempty"` // substring | word | wildcard
	Patterns  []string `json:"patterns,omitempty"`   // regex / name

	// Shared allow-list: exempt terms (words), allowed domains (links/allowlist),
	// or allowed invite codes/guild ids (invites).
	AllowList []string `json:"allow_list,omitempty"`

	// Links.
	LinkMode string   `json:"link_mode,omitempty"` // all | allowlist | blocklist
	Domains  []string `json:"domains,omitempty"`   // blocked domains (link_mode=blocklist)

	// Numeric thresholds (mentions/caps/emojis/newlines/zalgo/spoilers/attachments/account_age).
	Limit     int `json:"limit,omitempty"`
	MinLength int `json:"min_length,omitempty"` // caps: ignore messages shorter than this

	// Rate-based (spam/duplicates).
	Count  int `json:"count,omitempty"`  // events that trip the rule
	Window int `json:"window,omitempty"` // seconds

	// Mass-mention switches.
	Everyone bool `json:"everyone,omitempty"`
	Roles    bool `json:"roles,omitempty"`

	// Name trigger: which fields to scan (default "both").
	Scan string `json:"scan,omitempty"` // username | nick | both
}

// RuleAction is one effect applied when a rule fires. Type values are the
// Action* constants in catalog.go. Per-type field meanings:
//
//	delete         remove the offending message (message triggers only)
//	warn           record a warn case + DM the user (if DM-on-action is on)
//	timeout        Duration seconds (0 ⇒ 10m)
//	kick           remove the member
//	ban            DeleteDays (0-7) of message history; Duration>0 ⇒ temp-ban seconds
//	add_role       grant RoleID (e.g. a mute / quarantine role)
//	remove_role    revoke RoleID
//	send_message   post Message (Go template) to Channel ("" = trigger channel),
//	               auto-deleting after DeleteAfter seconds (0 = keep)
//	dm             DM the user Message (Go template)
//	add_points     add Points to the user's infraction heat (feeds escalation)
//
// Reason overrides the auto-generated audit/case reason when set.
type RuleAction struct {
	Type string `json:"type"`

	Duration   int `json:"duration,omitempty"`    // timeout/ban seconds
	DeleteDays int `json:"delete_days,omitempty"` // ban: purge N days (0-7)

	RoleID string `json:"role_id,omitempty"` // add_role / remove_role

	Message     string `json:"message,omitempty"`      // send_message / dm (Go template)
	Channel     string `json:"channel,omitempty"`      // send_message target
	DeleteAfter int    `json:"delete_after,omitempty"` // send_message auto-delete seconds

	Points int `json:"points,omitempty"` // add_points

	Reason string `json:"reason,omitempty"` // optional reason override
}

// Escalation is the cross-rule heat ladder. Infraction points awarded by
// add_points actions accumulate per user; the highest tier whose Points
// threshold the user's active total has crossed is applied automatically.
type Escalation struct {
	Enabled bool `json:"enabled"`
	// DecayHours is how long a point stays "active" before it stops counting
	// toward thresholds (0 ⇒ 24h).
	DecayHours int `json:"decay_hours"`
	// Tiers are the ladder rungs (sorted by Points ascending by the engine).
	Tiers []EscalationTier `json:"tiers"`
}

// EscalationTier is one rung of the ladder.
type EscalationTier struct {
	Points   int    `json:"points"`             // active total at/above which it fires
	Action   string `json:"action"`             // timeout | kick | ban
	Duration int    `json:"duration,omitempty"` // seconds (timeout action)
}

// DefaultAutomod returns a useful starter configuration: a handful of common
// rules enabled out of the box plus a sane escalation ladder. (Go does not allow
// two Default functions in one package, so the automod default is named
// explicitly.)
func DefaultAutomod() AutomodConfig {
	return AutomodConfig{
		IgnoreBots: true,
		IgnoreMods: true,
		Rules: []AutomodRule{
			{
				ID:      "rule_invites",
				Name:    "Block Discord invites",
				Enabled: true,
				Trigger: RuleTrigger{Type: TriggerInvites},
				Actions: []RuleAction{
					{Type: ActionDelete},
					{Type: ActionWarn, Reason: "Posting invite links is not allowed"},
					{Type: ActionAddPoints, Points: 1},
				},
			},
			{
				ID:      "rule_spam",
				Name:    "Message spam",
				Enabled: true,
				Trigger: RuleTrigger{Type: TriggerSpam, Count: 5, Window: 5},
				Actions: []RuleAction{
					{Type: ActionDelete},
					{Type: ActionTimeout, Duration: 600, Reason: "Sending messages too quickly"},
					{Type: ActionAddPoints, Points: 2},
				},
			},
			{
				ID:      "rule_mentions",
				Name:    "Mass mentions",
				Enabled: true,
				Trigger: RuleTrigger{Type: TriggerMentions, Limit: 6},
				Actions: []RuleAction{
					{Type: ActionDelete},
					{Type: ActionTimeout, Duration: 300, Reason: "Too many mentions"},
					{Type: ActionAddPoints, Points: 2},
				},
			},
			{
				ID:      "rule_everyone",
				Name:    "@everyone / @here pings",
				Enabled: true,
				// Limit 0 => trips on the first @everyone/@here (see detectMassMention).
				Trigger: RuleTrigger{Type: TriggerMassMention, Everyone: true, Limit: 0},
				Actions: []RuleAction{
					{Type: ActionDelete},
					{Type: ActionAddPoints, Points: 1},
				},
			},
		},
		Escalation: Escalation{
			Enabled:    true,
			DecayHours: 24,
			Tiers: []EscalationTier{
				{Points: 3, Action: "timeout", Duration: 600},
				{Points: 5, Action: "timeout", Duration: 3600},
				{Points: 8, Action: "kick"},
				{Points: 12, Action: "ban"},
			},
		},
	}
}
